-- expo — ported from expo/vscode-expo-theme (Expo Dark)
-- Managed by the `theme` CLI. Transparent bg so the wallpaper shows through.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "expo"

local p = {
  bg      = "NONE",     -- transparent
  solid   = "#111113",
  panel   = "#18191b",  -- pmenu / floats
  sel     = "#2e3135",
  cline   = "#18191b",
  fg      = "#edeef0",
  comment = "#777b84",
  punct   = "#696e77",
  gutter  = "#696e77",
  blue    = "#3b9eff",
  green   = "#3dd68c",
  orange  = "#f76b15",
  red     = "#e5484d",
  purple  = "#9a5cd0",
  pink    = "#de51a8",
  yellow  = "#ffca16",
}

local term = {
  "#1c1e21", "#e5484d", "#3dd68c", "#ffca16", "#3b9eff", "#de51a8", "#3aa8c9", "#edeef0",
  "#696e77", "#ff6369", "#4ee6a0", "#ffd84d", "#5aacff", "#e56fc0", "#5bc4e0", "#ffffff",
}
for i, col in ipairs(term) do vim.g["terminal_color_" .. (i - 1)] = col end

local hi = function(g, s) vim.api.nvim_set_hl(0, g, s) end
local groups = {
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.panel },
  FloatBorder = { fg = p.punct, bg = p.panel },
  FloatTitle = { fg = p.blue, bg = p.panel, bold = true },
  ColorColumn = { bg = p.cline },
  Cursor = { fg = p.solid, bg = p.fg },
  CursorLine = { bg = p.cline },
  CursorColumn = { bg = p.cline },
  CursorLineNr = { fg = p.fg, bold = true },
  LineNr = { fg = p.gutter },
  SignColumn = { bg = p.bg },
  Folded = { fg = p.comment, bg = p.cline },
  FoldColumn = { fg = p.gutter, bg = p.bg },
  VertSplit = { fg = p.sel },
  WinSeparator = { fg = p.sel },
  Visual = { bg = p.sel },
  Search = { fg = p.solid, bg = p.yellow },
  IncSearch = { fg = p.solid, bg = p.orange },
  CurSearch = { fg = p.solid, bg = p.orange },
  MatchParen = { fg = p.yellow, bold = true },
  NonText = { fg = p.sel },
  Whitespace = { fg = p.sel },
  EndOfBuffer = { fg = p.bg },
  Pmenu = { fg = p.fg, bg = p.panel },
  PmenuSel = { fg = p.fg, bg = p.sel, bold = true },
  PmenuSbar = { bg = p.sel },
  PmenuThumb = { bg = p.gutter },
  StatusLine = { fg = p.fg, bg = p.panel },
  StatusLineNC = { fg = p.comment, bg = p.panel },
  TabLine = { fg = p.comment, bg = p.bg },
  TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
  TabLineFill = { bg = p.bg },
  WinBar = { fg = p.fg, bg = p.bg },
  WinBarNC = { fg = p.comment, bg = p.bg },
  Title = { fg = p.blue, bold = true },
  Directory = { fg = p.blue },
  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.yellow },
  Question = { fg = p.green },
  QuickFixLine = { bg = p.sel, bold = true },

  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.blue },
  String = { fg = p.yellow },
  Character = { fg = p.yellow },
  Number = { fg = p.yellow },
  Boolean = { fg = p.yellow },
  Float = { fg = p.yellow },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.purple },
  Conditional = { fg = p.purple },
  Repeat = { fg = p.purple },
  Label = { fg = p.purple },
  Operator = { fg = p.punct },
  Keyword = { fg = p.purple },
  Exception = { fg = p.pink },
  PreProc = { fg = p.pink },
  Include = { fg = p.pink },
  Define = { fg = p.pink },
  Macro = { fg = p.pink },
  Type = { fg = p.green },
  StorageClass = { fg = p.pink },
  Structure = { fg = p.green },
  Typedef = { fg = p.green },
  Special = { fg = p.orange },
  SpecialChar = { fg = p.orange },
  Delimiter = { fg = p.punct },
  Tag = { fg = p.orange },
  Underlined = { underline = true },
  Todo = { fg = p.solid, bg = p.yellow, bold = true },
  Error = { fg = p.red },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.green },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnnecessary = { fg = p.comment },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.green },

  DiffAdd = { bg = "#12241b" },
  DiffChange = { bg = "#1e2436" },
  DiffDelete = { bg = "#2a1517" },
  DiffText = { bg = "#123a2b" },
  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },
  SignAdd = { fg = p.green },
  SignChange = { fg = p.blue },
  SignDelete = { fg = p.red },

  LspReferenceText = { bg = p.sel },
  LspReferenceRead = { bg = p.sel },
  LspReferenceWrite = { bg = p.sel },
  LspInlayHint = { fg = p.gutter, bg = p.panel },

  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.pink },
  ["@variable.parameter"] = { fg = p.blue },
  ["@variable.member"] = { fg = p.fg },
  ["@property"] = { fg = p.fg },
  ["@field"] = { fg = p.fg },
  ["@constant"] = { fg = p.blue },
  ["@constant.builtin"] = { fg = p.pink },
  ["@module"] = { fg = p.blue },
  ["@string"] = { fg = p.yellow },
  ["@string.escape"] = { fg = p.orange },
  ["@character"] = { fg = p.yellow },
  ["@boolean"] = { fg = p.yellow },
  ["@number"] = { fg = p.yellow },
  ["@function"] = { fg = p.blue },
  ["@function.builtin"] = { fg = p.purple },
  ["@function.call"] = { fg = p.blue },
  ["@function.method"] = { fg = p.blue },
  ["@function.method.call"] = { fg = p.blue },
  ["@constructor"] = { fg = p.green },
  ["@keyword"] = { fg = p.purple },
  ["@keyword.function"] = { fg = p.purple },
  ["@keyword.operator"] = { fg = p.punct },
  ["@keyword.return"] = { fg = p.pink },
  ["@keyword.import"] = { fg = p.pink },
  ["@keyword.conditional"] = { fg = p.pink },
  ["@keyword.repeat"] = { fg = p.pink },
  ["@operator"] = { fg = p.punct },
  ["@type"] = { fg = p.green },
  ["@type.builtin"] = { fg = p.pink },
  ["@attribute"] = { fg = p.red },
  ["@tag"] = { fg = p.orange },
  ["@tag.attribute"] = { fg = p.red },
  ["@tag.delimiter"] = { fg = p.punct },
  ["@punctuation"] = { fg = p.punct },
  ["@punctuation.bracket"] = { fg = p.punct },
  ["@punctuation.delimiter"] = { fg = p.punct },
  ["@punctuation.special"] = { fg = p.orange },
  ["@comment"] = { fg = p.comment, italic = true },
  ["@comment.todo"] = { fg = p.solid, bg = p.yellow, bold = true },
  ["@markup.heading"] = { fg = p.blue, bold = true },
  ["@markup.raw"] = { fg = p.yellow },
  ["@markup.link"] = { fg = p.green },
  ["@markup.link.url"] = { fg = p.blue, underline = true },
  ["@markup.strong"] = { fg = p.pink, bold = true },
  ["@markup.italic"] = { fg = p.green, italic = true },

  TelescopeNormal = { fg = p.fg, bg = p.panel },
  TelescopeBorder = { fg = p.punct, bg = p.panel },
  TelescopePromptNormal = { fg = p.fg, bg = p.panel },
  TelescopePromptBorder = { fg = p.punct, bg = p.panel },
  TelescopePromptTitle = { fg = p.blue, bold = true },
  TelescopeResultsTitle = { fg = p.blue, bold = true },
  TelescopePreviewTitle = { fg = p.green, bold = true },
  TelescopeSelection = { bg = p.sel, bold = true },
  TelescopeMatching = { fg = p.yellow, bold = true },

  CmpItemAbbrMatch = { fg = p.blue, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.blue, bold = true },
  BlinkCmpMenu = { fg = p.fg, bg = p.panel },
  BlinkCmpMenuBorder = { fg = p.punct, bg = p.panel },
  BlinkCmpLabelMatch = { fg = p.blue, bold = true },

  NeoTreeNormal = { fg = p.fg, bg = p.bg },
  NvimTreeNormal = { fg = p.fg, bg = p.bg },
  IblIndent = { fg = p.sel },
  IblScope = { fg = p.purple },
}
for g, s in pairs(groups) do hi(g, s) end
