-- lilac — ported from shubham-saudolla/Lilac-Theme (dark pastel purple)
-- Managed by the `theme` CLI. Transparent bg so the wallpaper shows through.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "lilac"

local p = {
  bg      = "NONE",     -- transparent
  solid   = "#080709",
  panel   = "#211d26",  -- pmenu / floats
  sel     = "#3f2a57",
  cline   = "#100e12",
  fg      = "#e0ceed",
  comment = "#614e6e",
  punct   = "#8e6da6",
  gutter  = "#3b3442",
  purple  = "#b657ff",  -- keywords / storage / types
  pink    = "#f5b0ef",  -- strings / functions
  peri    = "#a29dfa",  -- tags / periwinkle
  magenta = "#f25ae6",  -- numbers
  muted   = "#8e6da6",
  red     = "#f03e5f",
  amber   = "#e0a44e",  -- warnings (off-palette, for legibility)
}

local term = {
  "#151217", "#ba0e2e", "#a29dfa", "#b657ff", "#f5b0ef", "#8e6da6", "#8e69c9", "#ece1f4",
  "#3b3442", "#f03e5f", "#fefeff", "#e2bdff", "#ffffff", "#bfaccd", "#c7b4e4", "#ffffff",
}
for i, col in ipairs(term) do vim.g["terminal_color_" .. (i - 1)] = col end

local hi = function(g, s) vim.api.nvim_set_hl(0, g, s) end
local groups = {
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.panel },
  FloatBorder = { fg = p.punct, bg = p.panel },
  FloatTitle = { fg = p.purple, bg = p.panel, bold = true },
  ColorColumn = { bg = p.cline },
  Cursor = { fg = p.solid, bg = p.fg },
  CursorLine = { bg = p.cline },
  CursorColumn = { bg = p.cline },
  CursorLineNr = { fg = p.purple, bold = true },
  LineNr = { fg = p.gutter },
  SignColumn = { bg = p.bg },
  Folded = { fg = p.comment, bg = p.cline },
  FoldColumn = { fg = p.gutter, bg = p.bg },
  VertSplit = { fg = p.sel },
  WinSeparator = { fg = p.sel },
  Visual = { bg = p.sel },
  Search = { fg = p.solid, bg = p.pink },
  IncSearch = { fg = p.solid, bg = p.purple },
  CurSearch = { fg = p.solid, bg = p.purple },
  MatchParen = { fg = p.purple, bold = true },
  NonText = { fg = p.sel },
  Whitespace = { fg = p.sel },
  EndOfBuffer = { fg = p.bg },
  Pmenu = { fg = p.fg, bg = p.panel },
  PmenuSel = { fg = p.fg, bg = p.sel, bold = true },
  PmenuSbar = { bg = p.sel },
  PmenuThumb = { bg = p.gutter },
  StatusLine = { fg = p.fg, bg = p.panel },
  StatusLineNC = { fg = p.comment, bg = p.panel },
  TabLine = { fg = p.comment, bg = p.bg },
  TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
  TabLineFill = { bg = p.bg },
  WinBar = { fg = p.fg, bg = p.bg },
  WinBarNC = { fg = p.comment, bg = p.bg },
  Title = { fg = p.purple, bold = true },
  Directory = { fg = p.peri },
  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.amber },
  Question = { fg = p.peri },
  QuickFixLine = { bg = p.sel, bold = true },

  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.purple },
  String = { fg = p.pink },
  Character = { fg = p.pink },
  Number = { fg = p.magenta },
  Boolean = { fg = p.magenta },
  Float = { fg = p.magenta },
  Identifier = { fg = p.fg },
  Function = { fg = p.pink },
  Statement = { fg = p.purple },
  Conditional = { fg = p.purple },
  Repeat = { fg = p.purple },
  Label = { fg = p.purple },
  Operator = { fg = p.muted },
  Keyword = { fg = p.purple },
  Exception = { fg = p.purple },
  PreProc = { fg = p.peri },
  Include = { fg = p.purple },
  Define = { fg = p.purple },
  Macro = { fg = p.peri },
  Type = { fg = p.purple },
  StorageClass = { fg = p.purple },
  Structure = { fg = p.purple },
  Typedef = { fg = p.purple },
  Special = { fg = p.peri },
  SpecialChar = { fg = p.magenta },
  Delimiter = { fg = p.muted },
  Tag = { fg = p.peri },
  Underlined = { underline = true },
  Todo = { fg = p.solid, bg = p.purple, bold = true },
  Error = { fg = p.red },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.amber },
  DiagnosticInfo = { fg = p.peri },
  DiagnosticHint = { fg = p.muted },
  DiagnosticOk = { fg = p.peri },
  DiagnosticUnnecessary = { fg = p.comment },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.amber },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.peri },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.muted },

  DiffAdd = { bg = "#1c2340" },
  DiffChange = { bg = "#2a1f36" },
  DiffDelete = { bg = "#331523" },
  DiffText = { bg = "#3a2b52" },
  Added = { fg = p.peri },
  Changed = { fg = p.pink },
  Removed = { fg = p.red },
  GitSignsAdd = { fg = p.peri },
  GitSignsChange = { fg = p.pink },
  GitSignsDelete = { fg = p.red },
  SignAdd = { fg = p.peri },
  SignChange = { fg = p.pink },
  SignDelete = { fg = p.red },

  LspReferenceText = { bg = p.sel },
  LspReferenceRead = { bg = p.sel },
  LspReferenceWrite = { bg = p.sel },
  LspInlayHint = { fg = p.gutter, bg = p.panel },

  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.purple },
  ["@variable.parameter"] = { fg = p.fg },
  ["@variable.member"] = { fg = p.fg },
  ["@property"] = { fg = p.fg },
  ["@field"] = { fg = p.fg },
  ["@constant"] = { fg = p.purple },
  ["@constant.builtin"] = { fg = p.purple },
  ["@module"] = { fg = p.peri },
  ["@string"] = { fg = p.pink },
  ["@string.escape"] = { fg = p.magenta },
  ["@character"] = { fg = p.pink },
  ["@boolean"] = { fg = p.magenta },
  ["@number"] = { fg = p.magenta },
  ["@function"] = { fg = p.pink },
  ["@function.builtin"] = { fg = p.pink },
  ["@function.call"] = { fg = p.pink },
  ["@function.method"] = { fg = p.pink },
  ["@function.method.call"] = { fg = p.pink },
  ["@constructor"] = { fg = p.purple },
  ["@keyword"] = { fg = p.purple },
  ["@keyword.function"] = { fg = p.purple },
  ["@keyword.operator"] = { fg = p.muted },
  ["@keyword.return"] = { fg = p.purple },
  ["@keyword.import"] = { fg = p.purple },
  ["@keyword.conditional"] = { fg = p.purple },
  ["@keyword.repeat"] = { fg = p.purple },
  ["@operator"] = { fg = p.muted },
  ["@type"] = { fg = p.purple },
  ["@type.builtin"] = { fg = p.purple },
  ["@attribute"] = { fg = p.purple },
  ["@tag"] = { fg = p.peri },
  ["@tag.attribute"] = { fg = p.pink },
  ["@tag.delimiter"] = { fg = p.muted },
  ["@punctuation"] = { fg = p.muted },
  ["@punctuation.bracket"] = { fg = p.muted },
  ["@punctuation.delimiter"] = { fg = p.muted },
  ["@punctuation.special"] = { fg = p.magenta },
  ["@comment"] = { fg = p.comment, italic = true },
  ["@comment.todo"] = { fg = p.solid, bg = p.purple, bold = true },
  ["@markup.heading"] = { fg = p.purple, bold = true },
  ["@markup.raw"] = { fg = p.pink },
  ["@markup.link"] = { fg = p.peri },
  ["@markup.link.url"] = { fg = p.pink, underline = true },
  ["@markup.strong"] = { fg = p.purple, bold = true },
  ["@markup.italic"] = { fg = p.peri, italic = true },

  TelescopeNormal = { fg = p.fg, bg = p.panel },
  TelescopeBorder = { fg = p.punct, bg = p.panel },
  TelescopePromptNormal = { fg = p.fg, bg = p.panel },
  TelescopePromptBorder = { fg = p.punct, bg = p.panel },
  TelescopePromptTitle = { fg = p.purple, bold = true },
  TelescopeResultsTitle = { fg = p.purple, bold = true },
  TelescopePreviewTitle = { fg = p.pink, bold = true },
  TelescopeSelection = { bg = p.sel, bold = true },
  TelescopeMatching = { fg = p.pink, bold = true },

  CmpItemAbbrMatch = { fg = p.purple, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.purple, bold = true },
  BlinkCmpMenu = { fg = p.fg, bg = p.panel },
  BlinkCmpMenuBorder = { fg = p.punct, bg = p.panel },
  BlinkCmpLabelMatch = { fg = p.purple, bold = true },

  NeoTreeNormal = { fg = p.fg, bg = p.bg },
  NvimTreeNormal = { fg = p.fg, bg = p.bg },
  IblIndent = { fg = p.sel },
  IblScope = { fg = p.purple },

  -- which-key: keep the leader popup transparent so it blends with the
  -- wallpaper instead of falling back to the solid NormalFloat panel.
  -- (which-key remaps the float's Normal -> WhichKeyNormal via winhighlight.)
  WhichKeyNormal = { fg = p.fg, bg = p.bg },
  WhichKeyFloat = { bg = p.bg },
  WhichKeyBorder = { fg = p.punct, bg = p.bg },
  WhichKeyTitle = { fg = p.purple, bg = p.bg, bold = true },
}
for g, s in pairs(groups) do hi(g, s) end
